name: Publish

on:
  push:
    tags:        
      - 'v*'           # Push events to every tag not containing /

    # Pattern matched against refs/tags
jobs:
  build:
    runs-on: ubuntu-${{ github.ref }}

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore CheapSteam.UI/CheapSteam.UI/CheapSteam.UI.csproj
    - name: Publish Windows x64
      run: dotnet publish CheapSteam.UI/CheapSteam.UI/CheapSteam.UI.csproj --runtime win-x64 -p:PublishSingleFile=true --self-contained true -o ./bin/Release/WebApi/${{ github.ref }}/CheapSteam-${{ github.ref }}-win-x64 -c Release
    - name: Publish OSX x64
      run: dotnet publish CheapSteam.UI/CheapSteam.UI/CheapSteam.UI.csproj --runtime osx-x64 -p:PublishSingleFile=true --self-contained true -o ./bin/Release/WebApi/${{ github.ref }}/CheapSteam-${{ github.ref }}-osx-x64 -c Release
    - name: Publish Linux x64
      run: dotnet publish CheapSteam.UI/CheapSteam.UI/CheapSteam.UI.csproj --runtime linux-x64 -p:PublishSingleFile=true --self-contained true -o ./bin/Release/WebApi/${{ github.ref }}/CheapSteam-${{ github.ref }}-linux-x64 -c Release
    - name: zip files
      run: zip -r CheapSteam-${{ github.ref }}-win-x64.zip ./bin/Release/WebApi/${{ github.ref }}/CheapSteam-${{ github.ref }}-win-x64 && zip -r CheapSteam-${{ github.ref }}-osx-x64.zip ./bin/Release/WebApi/${{ github.ref }}/CheapSteam-${{ github.ref }}-osx-x64 && zip -r CheapSteam-${{ github.ref }}-linux-x64.zip ./bin/Release/WebApi/${{ github.ref }}/CheapSteam-${{ github.ref }}-linux-x64
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        draft: false
        prerelease: false
    - name: Upload Release Asset
      id: upload-release-asset-1 
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps 
        asset_path: ./CheapSteam-${{ github.ref }}-win-x64.zip
        asset_name: CheapSteam-${{ github.ref }}-win-x64.zip
        asset_content_type: application/zip
    - name: Upload Release Asset
      id: upload-release-asset-2 
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps 
        asset_path: ./CheapSteam-${{ github.ref }}-osx-x64.zip
        asset_name: CheapSteam-${{ github.ref }}-osx-x64.zip
        asset_content_type: application/zip
    - name: Upload Release Asset
      id: upload-release-asset-3 
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps 
        asset_path: ./CheapSteam-${{ github.ref }}-linux-x64.zip
        asset_name: CheapSteam-${{ github.ref }}-linux-x64.zip
        asset_content_type: application/zip
